### ISSUE TITLE
Fix the evaluation order of pipe expression by keeping it in the AST

### ISSUE THREAD

**Issue by MarcelGarus** [candy-lang/candy#292]
Currently, `foo 0 | (bar 1)` first evaluates `bar 1`, then `foo 0`, and then calls the result of `bar 1` with the result of `foo 0`. This is because pipes are not preserved in the AST, instead the expression gets lowered to the equivalent of `(bar 1) (foo 0)`.

We should keep pipe expressions in the AST and then fix the AST to HIR lowering so that the above code evaluates `foo 0`, then `bar 1`, and then calls the result of `bar 1` with the result of `foo 0`.

**Comment by skyz1** [comment]
`foo 0 | (bar 1)` actually gets lowered to the equivalent of `bar (foo 0) 1`. Is that a mistake? If I understand correctly only `foo 0 | bar 1` should get lowered to the equivalent of `bar (foo 0) 1`.

Should `foo 0 | (bar 1) 2` first evaluate `foo 0`, then `bar 1`, and finally call the result of `bar 1` with the result of `foo 0` and `2`? I.e:
```
temp = foo 0
(bar 1) temp 2
```

**Comment by JonasWanke** [comment]
That looks like a mistake, since the parentheses have higher precedence. cc @MarcelGarus 

Yes, that's the expected order. Roughly speaking: For each expression, we go from left to right, and for calls we first evaluate the receiver, then the arguments in order, and then execute the call itself.
