### ISSUE TITLE
Package support breaks candy on Windows

### ISSUE THREAD

**Issue by skyz1** [candy-lang/candy#402]
**Describe the bug**
#390 introduced a bug where the module resolution inside packages fails to detect if a file is located in the package on Windows. 

The underlying problem is the platform specific behavior of `fs::canonicalize` (see [the documentation](https://dev-doc.rust-lang.org/beta/std/fs/fn.canonicalize.html#platform-specific-behavior)). This function returns a UNC-Path prefixed with `\\?\` while `package.to_path` returns a DOS-Path without the prefix. `strip_prefix` then returns an error and the compiler thinks the file is not located in the package.

The [dunce crate](https://lib.rs/crates/dunce) was created to combat this issue, but converting the UNC-path to a URL and back to a file path seems to be a quick workaround.

```rust
let canonicalized = Url::from_file_path(canonicalized)
    .expect("Invalid file path.")
    .to_file_path()
    .expect("File path conversion error.");
```

**Comment by JonasWanke** [comment]
@skyz1 Can you please verify that the PR actually fixed this issue? I change all `fs::canonicalize(…)` invocations to `dunce::canonicalize(…)`, but don't have Windows installed to test it
