### ISSUE TITLE
Add higher-order functions for starting and ending scopes

### ISSUE THREAD

**Issue by MarcelGarus** [candy-lang/candy#855]
This pattern is all over the place in the AST to HIR compilation:

```rs
let reset_state = something.start.scope();
...
something.end_scope(reset_state);
```

Instead, we should use the `Drop` trait or, even better, have a higher-order function `create_scope`.

**Comment by JonasWanke** [comment]
I don't think the `Drop` trait is suited here, since that makes it harder to follow which scopes end where. Also, it doesn't work for the `end_scope(…)` in `ast_to_hir` which returns the inner `Body` that just got completed. But a higher-order function sounds good, maybe something like:

```rust
let inner_body = self.with_scope(|scope| {
  scope.push(expression);
});
```
