### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by flip111** [candy-lang/candy#878]
Does the compiler run on WebAssembly (wasm)? Is such feature planned?

**Comment by ctiedt** [comment]
This will likely be handled by one of the native backends. Currently, there is the semi-working Inkwell (i.e. LLVM-based) backend, but a Cranelift-based backend that will be easier to use is also in progress.

**Comment by flip111** [comment]
Thank you for your reply. Close the issue if you like or keep it open in case you like a reminder.

**Comment by JonasWanke** [comment]
I'm closing this since I just found our old tracking issue: #299. But I'm not sure when we'll get to implementing this
