### ISSUE TITLE
Make HirId smaller

### ISSUE THREAD

**Issue by MarcelGarus** [candy-lang/candy#890]
The HIR ID is quite big and inefficient. It contains many `Vec`s, which point to heap storage and again to Strings. All of those pointers take up 8 bytes each.

If we would instead serialize the HIR ID's path to a string (such as `Example$fibonacci:2:11:28`), we'd save a lot of memory and pointer indirections. All operations on HIR IDs would become simple memcpy/memcmps.

**Comment by skyz1** [comment]
Is it possible to assume that positional keys will always be at the end of the path. To be more precise, if there is a positional key in the path, will only positional keys follow?

**Comment by JonasWanke** [comment]
@skyz1 No. For example:

```candy
{
  assignment = 123
}
```

Here, I create a lambda (instead of a named function), so it gets a positional key. Inside of it, I can still create named keys:

```candy-hir
# HIR for module Examples:test
$use = { (non-fuzzable, but passes on responsibility) $use:relativePath ->
  $use:importedModule = relative to module Examples:test, use $use:relativePath
}
$0 = "Builtins"
$1 = call $use with $0
$2 = { (non-fuzzable) ->
  $2:0 = 123
  $2:assignment = $2:0
  $2:assignment#1 = $2:assignment
  $2:1 = Nothing
}
$3 = []
```

The package and module prefix if HIR IDs is not shown in this debug output, just the `keys`.

**Comment by skyz1** [comment]
I have also noticed that every time a HirId is created, the module information is copied. Couldn't refcounting be used to make all HirIds for one module point to the same memory location?
